### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received ~

### ISSUE THREAD

**Issue by petey** [atom/exception-reporting#31] opened 2017-02-10 21:48 UTC
[Enter steps to reproduce:]

1. Close an open tab
2. ...

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [exception-reporting](https://github.com/atom/exception-reporting) package 0.40.2

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1213:7)
    at Object.tildify (/app.asar/node_modules/exception-reporting/node_modules/fs-plus/lib/fs-plus.js:64:39)
    at /app.asar/node_modules/status-bar/lib/file-info-view.js:177:50)
    at /app.asar/node_modules/status-bar/lib/file-info-view.js:160:12)
    at /app.asar/node_modules/status-bar/lib/file-info-view.js:133:19)
    at /app.asar/node_modules/status-bar/lib/file-info-view.js:27:24
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/src/pane-container.js:348:27
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.setActiveItem (/app.asar/src/pane.js:300:22)
    at Pane.module.exports.Pane.activateItemAtIndex (/app.asar/src/pane.js:435:19)
    at Pane.module.exports.Pane.activatePreviousItem (/app.asar/src/pane.js:400:21)
    at Pane.module.exports.Pane.removeItem (/app.asar/src/pane.js:585:16)
    at Pane.module.exports.Pane.destroyItem (/app.asar/src/pane.js:658:16)
    at TabBarView.module.exports.TabBarView.closeTab (/app.asar/node_modules/tabs/lib/tab-bar-view.js:333:26)
    at HTMLDivElement.TabView.didClickCloseIcon (/app.asar/node_modules/tabs/lib/tab-bar-view.js:222:19)
```

### Commands

```
     -0:07.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-atom-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-fuzzy-grep 0.15.0 
atom-lcov 2.0.0 
atom-pair 2.0.10 
atom-yamljson 0.2.3 
cucumber 0.6.0 
docblockr 0.9.1 
docker 0.7.0 
dockerletion 0.2.0 
editorconfig 2.2.0 
ember-cli-helper 0.9.0 
ember-tabs 2.4.1 
file-icons 2.0.15 
git-plus 7.2.2 
git-projects 1.17.0 
git-tab-status 1.9.2 
git-time-machine 1.5.4 
go-debug 1.0.4 
go-plus 5.1.1 
go-signature-statusbar 1.2.0 
highlight-selected 0.12.0 
javascript-snippets 1.2.1 
language-babel 2.54.1 
language-chef 0.9.0 
language-cucumber 0.0.1 
language-docker 1.1.7 
linter 1.11.21 
linter-csslint 1.3.3 
linter-docker 0.1.4 
linter-eslint 8.1.0 
linter-js-yaml 1.2.6 
linter-jshint 3.0.2 
linter-jsonlint 1.3.0 
markdown-scroll-sync 2.1.2 
merge-conflicts 1.4.4 
pigments 0.39.0 
project-colorize 0.2.0 
project-plus 0.9.0 
regex-railroad-diagram 0.16.0 
sort-lines 0.14.0 
symbols-tree-view 0.13.2 
sync-settings 0.8.1 
tabs-to-spaces 1.0.3 
todo-show 1.9.0 
```

**Comment by kremalicious** [comment] 2017-02-15 11:21
Happening for me too with exact same stack trace on 1.14.2 x64/Mac OS X 10.12.3 and 1.15.0-beta2 x64/Mac OS X 10.12.3 when:

- closing a tab
- switching to another tab
- saving a file
- modifying a file in editor

So basically this bug makes using Atom impossible right now. Disabling the exception-reporting & status-bar package is a quick workaround.

**Comment by damieng** [comment] 2017-02-15 17:46
I think this is entirely in status bar on the other issue and that exception-reporter is just getting confused and thinking it is caused by itself. We'll track it on the other issue.

**Closed by damieng** 2017-02-15 17:46 UTC
Labels: bug, uncaught-exception

**Comment by xight** [comment] 2017-02-22 01:04
I met same problem using with fish-shell.
To solve problem, exec `chsh` and change default shell to POSIX shell, such as bash, zsh.
It worked on me.

**Comment by jaredallard** [comment] 2017-03-30 19:54
I get this same error when typing in the editor now, makes using it impossible. :(

**Comment by damieng** [comment] 2017-03-30 19:55
@jaredallard can you try the steps in https://github.com/atom/status-bar/issues/184#issuecomment-288506131 and let us know if it solves it for you.

**Comment by jaredallard** [comment] 2017-03-30 20:00
@damieng That works for me.
